Add missing dt_read_{un}lock()
LustreError: 1485:0:(osd_handler.c:2826:osd_xattr_get())
ASSERTION(osd_read_locked(env, obj) || osd_write_locked(env, obj)) failed
LustreError: 1485:0:(osd_handler.c:2826:osd_xattr_get()) LBUG
Pid: 1485, comm: mdt_01

Call Trace:
 [<ffffffffa073d835>] libcfs_debug_dumpstack+0x55/0x80 [libcfs]
 [<ffffffffa073dd67>] lbug_with_loc+0x47/0xb0 [libcfs]
 [<ffffffffa074741d>] libcfs_assertion_failed+0x2d/0x30 [libcfs]
 [<ffffffffa0e74031>] osd_xattr_get+0x1c1/0x1d0 [osd_zfs]
 [<ffffffffa0ce8800>] ? mdt_blocking_ast+0x0/0x230 [mdt]
 [<ffffffffa086de43>] dt_version_get+0x63/0x170 [obdclass]
 [<ffffffffa0d00010>] mdt_obj_version_get+0x100/0x170 [mdt]
 [<ffffffffa0d00b69>] mdt_version_get_check_save+0x39/0xe0 [mdt]
 [<ffffffffa0d010ce>] mdt_md_create+0x11e/0x5c0 [mdt]
 [<ffffffffa0017a90>] ? lprocfs_counter_add+0x140/0x1b2 [lvfs]
 [<ffffffffa0d01688>] mdt_reint_create+0x118/0x590 [mdt]
 [<ffffffffa0cff9e0>] mdt_reint_rec+0x40/0xb0 [mdt]
 [<ffffffffa09b4c54>] ? lustre_msg_get_flags+0x34/0x70 [ptlrpc]
 [<ffffffffa0cf6654>] mdt_reint_internal+0x364/0x6d0 [mdt]
 [<ffffffffa0cf6a04>] mdt_reint+0x44/0xc0 [mdt]
 [<ffffffffa0cee1cd>] mdt_handle_common+0x74d/0x12d0 [mdt]
 [<ffffffffa0ceee25>] mdt_regular_handle+0x15/0x20 [mdt]
 [<ffffffffa09c0a44>] ptlrpc_main+0xd14/0x1730 [ptlrpc]
 [<ffffffffa09bfd30>] ? ptlrpc_main+0x0/0x1730 [ptlrpc]
 [<ffffffff8100c14a>] child_rip+0xa/0x20
 [<ffffffffa09bfd30>] ? ptlrpc_main+0x0/0x1730 [ptlrpc]
 [<ffffffffa09bfd30>] ? ptlrpc_main+0x0/0x1730 [ptlrpc]
 [<ffffffff8100c140>] ? child_rip+0x0/0x20

Change-Id: Ie42d5fed91ed96d8c95d213d08edaa26c3449ab6