b=16909 Simplify MDT/OST service start message
I've resisted changing this message for quite some time but not today.
This message contains alot of information some of which is important
some of which really isn't.  I'm proposing the elimination of the less
important bits and the addition of a little more info the admins may
be interested in.

In particular the changes I've made are to drop lustre_cfg_string()
and simplify what is printed for the device name.  It used to be
(label/uuid) or just (uuid) if there was no label.  I've changed
this to print only the label when it exists and the uuid when it
does not.  I have also merged the device name in to this message
and dropped the other stray message with this info.

Finally I've broken the message in to two parts.  There was always
a message which would tell you if recovery was enabled or disabled.
But in practive we never saw it since obd_recovering was always set
so we saw the other message in the if () an obviously inferred that
recovery was enabled.  That made sense but I would still rather make
it explicit so I've pulled that message out of the if () so it is
always printed.  Then I've simplified the second message which
contains the details able how long recovery should take and make
sure it is only printed as before when we are recovering.

  Lustre: lc2-OST001f: Now serving dev (lc2-OST001f/
  bff4fc50-e3e2-acd1-4392- 940b80c1e9ad), but will be in
  recovery for at least 5:00, or until 73 clients reconnect.
  Lustre: lc2-OST001f: Server on device /dev/sda has started

Was changed too one of the following examples:

  Lustre: lc2-OST001f: Now serving lc2-OST001f on /dev/sda with recovery disabled

  Lustre: lc2-OST001f: Now serving lc2-OST001f on /dev/sda with recovery enabled
  Lustre: lc2-OST001f: Will be in recovery for at least 5:00, or until 73
  clients reconnect

Also as part of this patch I've updated the console filter to correctly
handle fake requests and squelched the lov_update_create_set() message
for the -ETIMEDOUT/-ENOTCONN case.

  LustreError: 7872:0:(lov_request.c:693:lov_update_create_set()) error
  creating fid 0x104c5e0b sub-object on OST idx 53/2: rc = -107