replace from_timer() with timer_container_of()
Fixes this build error with toss 5 kernel:
	In file included from /builddir/build/BUILD/lustre-2.15.8_1.llnl/libcfs/include/libcfs/libcfs.h:45,
			 from /builddir/build/BUILD/lustre-2.15.8_1.llnl/lnet/klnds/kfilnd/kfilnd.h:72,
			 from /builddir/build/BUILD/lustre-2.15.8_1.llnl/lnet/klnds/kfilnd/kfilnd_tn.h:34,
			 from /builddir/build/BUILD/lustre-2.15.8_1.llnl/lnet/klnds/kfilnd/kfilnd_tn.c:32:
	/builddir/build/BUILD/lustre-2.15.8_1.llnl/lnet/klnds/kfilnd/kfilnd_tn.c: In function 'kfilnd_tn_timeout':
	/builddir/build/BUILD/lustre-2.15.8_1.llnl/libcfs/include/libcfs/linux/linux-time.h:238:9: error: implicit declaration of function 'from_timer'; did you mean 'mod_timer'? [-Werror=implicit-function-declaration]
	  238 |         from_timer(var, callback_timer, timer_fieldname)
	      |         ^~~~~~~~~~
	/builddir/build/BUILD/lustre-2.15.8_1.llnl/lnet/klnds/kfilnd/kfilnd_tn.c:527:41: note: in expansion of macro 'cfs_from_timer'
	  527 |         struct kfilnd_transaction *tn = cfs_from_timer(tn, data, timeout_timer);
	      |                                         ^~~~~~~~~~~~~~

Redhat backported a linux 6.16 patch that renamed from_timer() to the
new name as part of an effort to standardize names across the kernel.

This change is part of a much larger commit in master, which I did not
backport due to its size.

	commit aab46afbef555051f9c0907cb0b066e4a6e56aa5
	Author: James Simmons <jsimmons@infradead.org>
	Date:   Sat Feb 14 10:59:18 2026 -0500

	    LU-19179 build: remove all remaining libcfs 4.X kernel support

	    All support for kernels before 5.0 are removed from the libcfs
	    layer.

Signed-off-by: Olaf P. Faaland <faaland1@llnl.gov>