TOSS-5943 uninitialized variable fixup
The build can fail with the following error:

In file included from /builddir/build/BUILD/lustre-2.12.9_6.llnl/libcfs/include/libcfs/libcfs.h:44:0,
                 from /builddir/build/BUILD/lustre-2.12.9_6.llnl/lnet/klnds/o2iblnd/o2iblnd.h:80,
                 from /builddir/build/BUILD/lustre-2.12.9_6.llnl/lnet/klnds/o2iblnd/o2iblnd_cb.c:37:
/builddir/build/BUILD/lustre-2.12.9_6.llnl/lnet/klnds/o2iblnd/o2iblnd_cb.c: In function 'kiblnd_post_tx_locked':
/builddir/build/BUILD/lustre-2.12.9_6.llnl/libcfs/include/libcfs/libcfs_debug.h:158:33: error: 'invalidate_succeeded' may be used uninitialized in this function [-Werror=maybe-uninitialized]
                 libcfs_debug_msg(&msgdata, format, ## __VA_ARGS__);

This is because it is only assigned within one branch of an if statement,
but is used in a CDEBUG which occurs outside all branches.