LU-13089 osc: revert "glimpse - search for active lock"
Revert "LU-11670 osc: glimpse - search for active lock"

This could cause assertion failures like below:

LustreError: 13759:0:(ldlm_lock.c:213:ldlm_lock_put())
		ASSERTION((((( lock))->l_flags & (1ULL << 50)) != 0) ) failed:
LustreError: 10188:0:(ldlm_lock.c:205:ldlm_lock_put())
		ASSERTION( atomic_read(&lock->l_refc) > 0 ) failed:
LustreError: 10188:0:(ldlm_lock.c:205:ldlm_lock_put()) LBUG

A glimpse cb race with cancel cb.

This reverts commit 2548cb9e32bfca897de577f88836629f72641369

Conflicts:
	lustre/tests/sanityn.sh

Cherry-picked-from: 37205c60bb2d99363a0c9dbf29d8f4fd684b6fab
Cherry-picked-from-change: https://review.whamcloud.com/#/c/39819
Cherry-picked-from-patch: 1
Cherry-picked-from-branch: b2_12
Cherry-picked-from-status: Maloo +1, No Review
Cherry-picked-from-notes: Removed test_103

Signed-off-by: Bobi Jam <bobijam@whamcloud.com>
Change-Id: I12063d0b3f1411e0d44393823a3e220cea6567d5