fix string overflow warning in name_create_mdt()
Switch to snprintf().

fixes warning:
> lustre/mgs/mgs_llog.c:1539:30: error: sprintf may write a
> terminating nul past the end of the destination
> [-Werror=format-overflow=]
>   sprintf(mdt_index, "-MDT%04x", i);

Signed-off-by: Olaf Faaland <faaland1@llnl.gov>